### health check

GET http://localhost:8888/ping

### save car

POST http://localhost:8888/api/cars 
content-type: application/json

{
  "year": 1989,
  "make": "bmw",
  "model": "3m",
  "color": "beige"
}

### list cars

GET http://localhost:8888/api/cars

### get car by specific carId

GET http://localhost:8888/api/cars/8